"use client"
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZTelvP8p8lG
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {useState} from 'react'
import {YoutubeMp3Convert} from '@/components/youtube-mp3-convert'

export function YouTube() {
  const [convert, setConvert] = useState(false)
  return (
      <div className="container md:px-4 px-0 rounded md:w-2/3 w-[93%] mx-auto">
        <header className="flex md:flex-row flex-col md:justify-between justify-start md:items-center items-start py-4">
          <h1 className="md:text-3xl text-xl  font-bold text-[#333333]">OnlyMP3</h1>
        </header>
        <section className="mt-8 border border-gray-200 md:p-16 p-5">
          <h2 className="md:text-4xl text-xl font-bold text-center text-[#333333] mb-4">YouTube to MP3
            Converter</h2>
          <div className="flex justify-center items-center space-x-4">
            <Input placeholder="Paste YouTube link here..."/>
            <Button onClick={() => setConvert(!convert)} className="bg-red-500 text-white hover:bg-red-600">Convert</Button>
          </div>
        </section>
        {convert ? (
            <YoutubeMp3Convert/>
        ) : (
            <main>
              <p className="text-left text-[#333333] my-6 w-11/12 mx-auto">
                By using our service, <br className={"block md:hidden"} />you are accepting our
                <Link className="text-red-500 hover:text-red-600 pl-1" href="#">
                  terms of service
                </Link>
                .{"\n                  "}
              </p>
              <section className="md:w-full w-[95%] mx-auto">
                <h3 className="md:text-3xl text-xl font-bold text-[#333333] mb-4 underline underline-offset-4">Best Free YouTube MP3 Downloader</h3>
                <p className="text-[#333333] md:leading-[35px] leading-[28px]">
                  OnlyMP3 web app helps you easily convert YouTube videos to MP3 music files with just one click. You
                  don't
                  have to Signup or install any software to perform the conversion. It's as easy as apple pie. We also
                  support
                  an unlimited number of videos to convert into audio files and save them to your Dropbox account. To
                  convert
                  a YT video, you just have to copy and paste the video URL into our YouTube MP3 converter tool and we
                  will
                  auto convert the Video to Audio file, You can also click the Dropbox button to save the file to the
                  cloud
                  platform. Enjoy unlimited conversion of music from youtube in the best available quality. It’s a
                  completely
                  free and secure service. Learn more about OnlyMP3 on <Link className={"text-red-500 hover:underline"}
                                                                             href={"https://www.tecklinker.com/"}>https://www.tecklinker.com/</Link>
                </p>
              </section>
            </main>
        )}
      </div>
  )
}
