"use client"
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZTelvP8p8lG
 */
import { Button } from "@/components/ui/button"
import {useState} from 'react'
import {YoutubeMp3Convert} from '@/components/youtube-mp3-convert'
import {cn} from '@/lib/utils'
import * as React from 'react'
import {convertMp3} from '@/lib/endpoint'
import SiteExplain from '@/components/site-explain'
import DownloadStep from '@/components/download-step'

export type languageType = "jp" | "en"

export function YouTube() {
  const [convert, setConvert] = useState(false)
  const [url, setUrl] = useState<string>("")
  const [response, setResponse] = useState<{file_name: string, thumbnail: string, title: string, duration: string, filesize: string}>({file_name: "aa", thumbnail: "aa", title: "aa", duration: "aaa", filesize:"zzz"})

  const [loading, setLoading] = useState(true);

  const upload = async () => {
    if (url === "")return
    setLoading(true)
    setConvert(true)
    const mp3 = await convertMp3(url)
    setResponse(mp3)
    setLoading(false)
  }

  const anotherVideo = (flag: boolean) => {
    setConvert(flag)
    setUrl("")
  }


  const [language, setLanguage] = useState<languageType>("en")

  return (
      <div className="container md:px-4 px-0 rounded md:w-2/3 w-[93%] mx-auto">
        <header className="flex items-center justify-between py-4 px-3">
          <h1 className="md:text-3xl text-xl  font-bold text-[#333333]">KoheiMP3</h1>
          <Button onClick={() => setLanguage(language === "en" ? "ja" as languageType : "en" as languageType)} className="bg-red-500 text-white hover:bg-red-600">{language === "en" as languageType ? "日本語" : "English"}</Button>
        </header>

        {convert ? (
            <YoutubeMp3Convert
                duration={response.duration}
                fileSize={response.filesize}
                url={response.file_name}
                thumbnail={response.thumbnail}
                title={response.title}
                videoUrl={url}
                setAnotherVideo={anotherVideo}
                loading={loading}
            />
        ) : (
            <div>
              <section id={"convert"} className="mt-8 border border-gray-200 md:p-16 p-5">
                <h2 className="md:text-4xl text-xl font-bold text-center text-[#333333] mb-4">YouTube to MP3
                  Converter</h2>

                <div className="flex justify-center items-center space-x-4">
                  <input
                      type={"text"}
                      className={cn(
                          "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
                      )}
                      value={url}
                      placeholder={"YouTube url is Here"}
                      onChange={(e) => setUrl( e.target.value )}
                  />
                  <Button onClick={() => upload()} className="bg-red-500 text-white hover:bg-red-600">Convert</Button>
                </div>
              </section>
              <section className={"mt-14"}>
                <div className="md:w-full w-[95%] mx-auto">
                  <h3 className="md:text-3xl text-xl font-bold text-center text-[#333333] mb-4 underline underline-offset-4">
                    {language === "ja" as languageType ? "最高品質のYouTube MP3変換サイト" : "Best Free YouTube MP3 Downloader"}
                  </h3>
                  <p className={`text-[#333333] md:leading-[35px] leading-[28px] ${language === "en" as languageType ? "block" : "hidden"}`}>
                    Effortlessly convert YouTube videos to MP3 music files with OnlyMP3, a user-friendly web app.
                    Experience the simplicity of transforming your favorite YouTube content into high-quality audio with
                    just a single click - no signup or software installation required. Our service is optimized for
                    unlimited conversions, allowing you to transform any number of videos into MP3 files with ease. To
                    start, simply copy and paste the YouTube video URL into our efficient YouTube to MP3 converter. The
                    process is automatic, converting the video to an audio file in moments. Enjoy the best quality audio
                    conversions from YouTube, completely free and secure.
                  </p>
                  <p className={`text-[#333333] md:leading-[35px] leading-[28px] ${language === "ja" as languageType ? "block" : "hidden"}`}>
                    OnlyMP3は、YouTube動画をMP3音楽ファイルに簡単に変換できる使いやすいウェブアプリです。このサービスにはサインアップやソフトウェアのインストールは必要ありません。私たちのサービスは無制限の変換をサポートし、任意の数のビデオをMP3ファイルに簡単に変換することができます。使用方法は簡単です。YouTube動画のURLをコピーして、MP3変換ソフトに貼り付けるだけです。プロセスは自動的で、瞬時にビデオをオーディオファイルに変換します。最高品質のオーディオで、YouTubeからの変換を完全無料かつ安全に楽しむことができます。
                  </p>
                </div>
              </section>

              <section id={"site-explain"}>
                <SiteExplain language={language}/>
              </section>

              <section id={"site-explain"}>
                <DownloadStep language={language}/>
              </section>
            </div>
        )}
      </div>
  )
}
